name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Needed for npm 2FA with provenance (optional)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Set package.json version from release tag
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          VERSION="${TAG_NAME#v}"  # strip leading 'v' if present
          echo "Setting package.json version to $VERSION"
          npm version --no-git-tag-version "$VERSION"
          echo "Updated version:"
          node -p "require('./package.json').version"

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: |
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
            if echo "$TAG_NAME" | grep -qi "beta"; then
              echo "Publishing with tag: beta"
              npm publish --tag beta --access public
            else
              echo "Publishing with tag: alpha"
              npm publish --tag alpha --access public
            fi
          else
            echo "Publishing as latest (stable release)"
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
